#!/bin/sh

# These arne't included until it's installed. Once that happens we can use the scripts 
# like they were always there.
PATH=${HOME}/.dotfiles/config:${HOME}/.dotfiles/bin:$PATH

# Run the install process.
. ${HOME}/.dotfiles/config/install

# Generate the aliases
#${HOME}/.dotfiles/bin/generate-aliases

# Copy over the .osx file and restart finder
#${HOME}/.dotfiles/osx2

# Copy over the bash_profile to the user directory.
#cp "${HOME}/.dotfiles/config/bash_profile" "${HOME}/.bash_profile"

# Create the custom directories.
mkdir -p ${HOME}/.dotfiles/.custom/scripts
mkdir -p ${HOME}/.dotfiles/.custom/other