#!/bin/sh
# Hey, you are actually in the .bashrc. Don't forget that.

# Some quick paths to use globally in include (source) files into bash scripts.
export BASH_SILENCE_DEPRECATION_WARNING=1
export DOTFILES="$HOME/.dotfiles"
export DOTFILES_CONFIG="$HOME/.dotfiles/config/bash"
export DOTFILES_BIN="$HOME/.dotfiles/bin"
export DOTFILES_CUSTOM="$HOME/.dotfiles/custom"
export BASH_CONSTS="$HOME/.dotfiles/config/constants"
export BASH_FUNCTIONS="$HOME/.dotfiles/config/bash_functions"
export OO_APPLICATION_PATH="/Applications"
export OO_CACHE_FILE="${DOTFILES}/data/oo.cache"
export EDITOR=vim
export CATALINA_HOME=/Applications/Developer/Tomcat
export HISTTIMEFORMAT="[%h/%d - %H:%M:%S] "
export LC_ALL="en_US.UTF-8"
export LANG="en_US"
export FIGNORE=DS_Store #Ignore the DS Store files when using bash.
export TERM=xterm-256color

# Now do some includes.
. $DOTFILES_CONFIG/bash_includes

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults

# Add 'killall' tab completion for common apps
complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal Twitter" killall

# # If possible, add tab completion for many more commands
# [ -f /etc/bash_completion ] && source /etc/bash_completion

PS1="$USERNAME [$GREEN$PATH_SHORT$YELLOW\$(parse_git_branch)$RED\$(parse_git_dirty)$RESET]: "

set completion-ignore-case on

export PATH=/opt/local/bin:/opt/local/sbin:$JOINED_PATHS:$PATH

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

