#!/bin/sh

############################################################
# ALIASES
############################################################

if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # OS X `ls`
	colorflag="-G"
fi

# INCLUDE THE WEBSERVER CONSTANTS FOR USE ELSEWHERE.
# . $WEBSERVER_CONSTS

# http://www.cyberciti.biz/tips/bash-aliases-mac-centos-linux-unix.html

# Emoticons
alias shrug="echo \"¯\\_(ツ)_/¯\" | tr -d '\n' | pbcopy"

# Keep settings files in sync. Can only be run from ~
alias syncup="sh .scripts/sync-settings-up.sh"
alias syncdown="sh .scripts/sync-settings-down.sh"

# GENERAL ALIASES
alias l="ls -aGl"
alias la="ls -la"
alias lsd="ls -la | egrep '^d'"

alias mkdir="mkdir -p"
alias ..="cdup"
alias df="cd ~/.dotfiles"
alias ep="explode-path"
alias projects="cd ~/Projects"
alias scratch="cd ~/Projects/scratch"
alias dashes="echo \"-------------------------------------------------\" | tr -d '\n' | pbcopy"

## CONVENIENCE
alias archive="tar -zcvf"
alias unarchive="tar -zxvf"
alias size="du -sh"
alias ack="ack -i"
alias pmd="${HOME}/.dotfiles/bin/pmd/bin/run.sh pmd"

# GOTO SPECIFIC FOLDERS
alias docs="cd ~/Documents"
alias proj="cd ~/Projects"
alias apps="cd /Applications"
alias dl="cd ~/Downloads"
alias desk="cd ~/Desktop"

# SSH.
alias readdssh="ssh-add ~/.ssh/id_rsa"

# OPEN SPECIFIC FOLDERS
alias odocs="open ~/Documents/"
alias odl="open ~/Downloads/"
alias odesk="open ~/Desktop/"
alias oproj="open ~/Projects"

## WEB DEVELOPMENT
alias ehosts="vim /etc/hosts"
alias rmraf="find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +; npm i"
alias lipsum="echo -n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum lacinia egestas. Nullam auctor tortor euismod turpis egestas pretium. Aliquam ullamcorper nulla diam, a fermentum velit vehicula non. Pellentesque egestas enim vitae pellentesque pulvinar. Nam placerat dictum mattis. Nunc non augue molestie, ullamcorper dui eu, interdum nunc. In ac aliquet sapien. Cras viverra luctus nisl, nec iaculis mauris laoreet sed. Etiam eu tortor nec mauris semper accumsan at at turpis.  | pbcopy; echo copied"
alias mclipsum='echo -n Test 1, 2. Test 1, 2. Test 1, 2, 3, 4. Hello? Hello? Anyone there? Time to read from the metro. Hub docs go after Ronald McDonald. Testing? Testing? All done. | pbcopy; echo mccopied'

# GENERATED & CUSTOM ALIASES
source $HOME/.dotfiles/custom/other/custom-aliases

# DOCKER SPECIFIC
alias docker-service="docker service ls --format \"{{.ID}}: [{{.Replicas}}] {{.Name}}\""
alias ds="docker service ls --format \"{{.ID}}: [{{.Replicas}}] {{.Name}}\""
alias drm="docker service rm"

## GIT SPECIFIC
alias ga='git add'
alias gpl='git pull'
alias gf='git fetch --tags --all'
alias gl='git log'
alias gs='git status'
alias gb='git branch'
alias gc='git commit -m'
alias gcl='git clone'
alias gco='git checkout'
alias grh='git reset --hard HEAD'
alias gpom='git push origin master'
alias gpod='git push origin dev'
alias gp="git push origin HEAD"
alias gcam="git commit -am"
alias gm="git commit -m"
alias grm="git branch -D"
alias grmall="git branch | xargs git branch -D"
alias gdab="git checkout master && git branch | grep -v "master" | xargs git branch -D; git fetch"
alias gw="git describe --tags"
alias grs='sudo git-rebuild-source'
alias grmm='git branch -D master; gco master'
alias gitassume="git update-index --assume-unchanged"
alias gitunassume="git update-index --no-assume-unchanged"

# Temporarilly ignore files.
# http://bit.ly/1MoJCCO && http://bit.ly/1gLPpFu
alias git-unchanged="git update-index --assume-unchanged"
alias git-nounchanged="git update-index --no-assume-unchanged"
alias gig="git update-index --assume-unchanged"

if [ -f $HOME/.dotfiles/bin/git-completion.bash ]; then
   source $HOME/.dotfiles/bin/git-completion.bash
   __git_complete ga _git_add
   __git_complete gp _git_push
   __git_complete gpl _git_pull
   __git_complete gf _git_fetch
   __git_complete gl _git_log
   __git_complete gs _git_status
   __git_complete gd _git_diff
   __git_complete gb _git_branch
   __git_complete gc _git_commit
   __git_complete gcl _git_clone
   __git_complete gco _git_checkout
fi
