#!/bin/sh

############################################################
# ALIASES
############################################################

if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # OS X `ls`
	colorflag="-G"
fi

# INCLUDE THE WEBSERVER CONSTANTS FOR USE ELSEWHERE.
# . $WEBSERVER_CONSTS

# http://www.cyberciti.biz/tips/bash-aliases-mac-centos-linux-unix.html

# Keep settings files in sync. Can only be run from ~
alias syncup="sh .scripts/sync-settings-up.sh"
alias syncdown="sh .scripts/sync-settings-down.sh"

# GENERAL ALIASES
alias l="ls -aGl"
alias lsd="ls -l | egrep '^d'"
alias mkdir="mkdir -p"
alias ..="cdup"
alias ebash="e ~/.bashrc"
alias ealias="emacs ~/.dotfiles/config/bash/bash_alias"
alias epaths="emacs ~/.dotfiles/config/bash/bash_dynamic_paths"
alias htdocs="cd /var/www"
alias www="cd /var/www"
alias spikes="cd /var/www/spikes"
alias ospikes="open /var/www/spikes"
alias maven="mvn"
alias etrash="rm -rf ~/.Trash/*"
alias am="oo \"activity monitor\""
alias dotf="cd ~/.dotfiles"
alias dotfiles="cd ~/.dotfiles"
alias ep="explode-path"
alias cpwd="pwd | pbcopy"
alias ntab="open . -a iterm"

## EMACS
alias e="emacs"
alias emacs="emacs -nw --debug-init"
alias myemacs="cd ~/.my-emacs"
alias eemacs="emacs ~/.emacs"
alias emacsd="cd ~/.emacs.d/"
alias estartup="emacs ~/.dotfiles/bin/startup"
alias makeemacs="curl -fsSkL http://bit.ly/1vT08Qr | sh; curl -fsSkL http://bit.ly/1vT0836 | sh"
alias myemacs-clearelc="find .my-emacs/ -name "*.elc" -exec rm {} \;"

## CONVENIENCE
alias archive="tar -zcvf"
alias unarchive="tar -zxvf"
alias size="du -sh"
alias ack="ack -i"

## APPS
alias calc="oo calculator"
alias ff="oo firefox"
alias text="oo textedit"
alias sublime="open -a sublime.app"
alias irc='irssi'

### MYSQL
alias umcli="open -e ~/.useful/mysql/cli.txt"
alias umcounting="open -e ~/.useful/mysql/counting.txt"
alias ummisc="open -e ~/.useful/mysql/misc.txt"
alias umcheats="open -e ~/.useful/mysql/mysql-cheatsheet.txt"
alias umpermissions="open -e ~/.useful/mysql/permissions.txt"
alias umsubselects="open -e ~/.useful/mysql/subselects.txt"
alias mesql="mysql -uroot -proot"
alias medump="mysqldump -uroot -proot"

# GOTO SPECIFIC FOLDERS
alias docs="cd ~/Documents"
alias music="cd ~/Music"
alias pics="cd ~/Pictures"
alias proj="cd ~/Projects"
alias apps="cd /Applications"
alias dl="cd ~/Downloads"
alias desk="cd ~/Desktop"
alias df="cd ~/.dotfiles"

alias readdssh="ssh-add ~/.ssh/id_rsa"

# OPEN SPECIFIC FOLDERS
alias odocs="open ~/Documents/"
alias omusic="open ~/Music/"
alias opics="open ~/Pictures/"
alias oapps="open /Applications/"
alias odl="open ~/Downloads/"
alias odesk="open ~/Desktop/"
alias oproj="open ~/Projects"
alias ohtdocs="open /var/www"
alias appsdevel="open /Applications/Developer"

## WEB DEVELOPMENT
alias mamp="cd /Applications/MAMP/"
alias clean_xprof="rm -rf /Users/avillanueva/Projects/XHProf-Output/*"
alias webserver_paths="less ${DOTFILES}/config/webserver/paths"
alias memcache="memcached -d"

## DRUPAL
alias dru='' # Default Drupal stuff.
alias en='drush en -y'
alias dis='drush dis -y'
alias cc='drush cc all'

# GENERATED & CUSTOM ALIASES
# source $HOME/.dotfiles/data/generated-aliases
source $HOME/.dotfiles/custom/other/custom-aliases

# WORKING WITH CUSTOM STUFF
alias ocustom="open ${DOTFILES}/custom"
alias escripts="open ${DOTFILES}/custom/scripts"

alias lipsum="echo -n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum lacinia egestas. Nullam auctor tortor euismod turpis egestas pretium. Aliquam ullamcorper nulla diam, a fermentum velit vehicula non. Pellentesque egestas enim vitae pellentesque pulvinar. Nam placerat dictum mattis. Nunc non augue molestie, ullamcorper dui eu, interdum nunc. In ac aliquet sapien. Cras viverra luctus nisl, nec iaculis mauris laoreet sed. Etiam eu tortor nec mauris semper accumsan at at turpis.  | pbcopy; echo copied"
alias mclipsum='echo -n Test 1, 2. Test 1, 2. Test 1, 2, 3, 4. Hello? Hello? Anyone there? Time to read from the metro. Hub docs go after Ronald McDonald. Testing? Testing? All done. | pbcopy; echo mccopied'

## GIT SPECIFIC
alias ga='git add'
alias gpl='git pull'
alias gf='git fetch --tags'
alias gl='git log'
alias gs='git status'
alias gb='git branch'
alias gc='git commit -m'
alias gcl='git clone'
alias gco='git checkout'
alias gpom='git push origin master'
alias gpod='git push origin dev'
alias gp="git push origin HEAD"
alias gcam="git commit -am"
alias grm="git branch -D"
alias grmall="git branch | xargs git branch -D"
alias gdab="git checkout master && git branch | grep -v "master" | xargs git branch -D; git fetch"
alias gw="git describe --tags"
alias grs='sudo git-rebuild-source'
alias grmm='git branch -D master; gco master'

# Temporarilly ignore files.
# http://bit.ly/1MoJCCO && http://bit.ly/1gLPpFu
alias git-unchanged="git update-index --assume-unchanged"
alias git-nounchanged="git update-index --no-assume-unchanged"
alias gig="git update-index --assume-unchanged"

if [ -f $HOME/.dotfiles/bin/git-completion.bash ]; then
   source $HOME/.dotfiles/bin/git-completion.bash
   __git_complete ga _git_add
   __git_complete gp _git_push
   __git_complete gpl _git_pull
   __git_complete gf _git_fetch
   __git_complete gl _git_log
   __git_complete gs _git_status
   __git_complete gd _git_diff
   __git_complete gb _git_branch
   __git_complete gc _git_commit
   __git_complete gcl _git_clone
   __git_complete gco _git_checkout
fi
