#!/bin/sh
# Contains a link to the bash_rc.

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

##
# Your previous /Users/alibresinn/.bash_profile file was backed up as /Users/alibresinn/.bash_profile.macports-saved_2025-07-14_at_11:08:42
##

# MacPorts Installer addition on 2025-07-14_at_11:08:42: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
