#!/bin/sh

############################################################
# ALIASES
############################################################

if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # OS X `ls`
	colorflag="-G"
fi

# INCLUDE THE WEBSERVER CONSTANTS FOR USE ELSEWHERE.
. $WEBSERVER_CONSTS

# http://www.cyberciti.biz/tips/bash-aliases-mac-centos-linux-unix.html

# Keep settings files in sync. Can only be run from ~
alias syncup="sh .scripts/sync-settings-up.sh"
alias syncdown="sh .scripts/sync-settings-down.sh"

# GENERAL ALIASES
alias l="ls -aGl"
alias lsd="ls -l | egrep '^d'"
alias ..="cdup"
alias sbash="source ~/.bash_profile"
alias ebash="edit ~/.bash_profile"
alias ealias="edit ~/.dotfiles/config/bash_alias"
alias epaths="edit ~/.dotfiles/config/bash_dynamic_paths"
alias htdocs="cd /var/www"
alias spikes="cd ~/Projects/Web-Applications/spikes"
alias pushnight="oo adium; oo mail; oo chrome;"
alias maven="mvn"
alias etrash="rm -rf ~/.Trash/*"
alias am="oo activity monitor"
alias dotf="cd ~/.dotfiles"
alias emacs="emacs -nw"
alias eemacs="edit ~/.emacs"

alias ep="explode-path"

## CONVENIENCE
alias arhive="tar -zcvf"
alias unarchive="tar -zxvf"
alias size="du -sh"

## APPS
alias calc="oo calculator"
alias ff="oo firefox"
alias text="oo textedit"

## CHEAT-SHEETS
alias uu="open ~/.dotfiles/useful"
alias uuseful="open ~/.dotfiles/useful"
alias udrush="open -e ~/.useful/bash/drush.txt"
#alias useful="open -e ~/.useful/bash/useful-commands.txt"
alias uarchive="open -e ~/.useful/bash/archive.txt"
alias ucron="open -e ~/.useful/bash/cron.txt"
alias udates="open -e ~/.useful/bash/dates.txt"
alias uemail="open -e ~/.useful/bash/email.txt"
alias ufile-editing="open -e ~/.useful/bash/file-editing.txt"
alias ufile-system="open -e ~/.useful/bash/file-system.txt"
alias ufiles="open -e ~/.useful/bash/files.txt"
alias uinternet="open -e ~/.useful/bash/internet.txt"
alias umisc="open -e ~/.useful/bash/misc.txt"
alias uregex="open -e ~/.useful/bash/regex.txt"
alias usystem="open -e ~/.useful/bash/system.txt"
alias usvn="open ~/.useful/svn/paths.txt"

### MYSQL
alias umcli="open -e ~/.useful/mysql/cli.txt"
alias umcounting="open -e ~/.useful/mysql/counting.txt"
alias ummisc="open -e ~/.useful/mysql/misc.txt"
alias umcheats="open -e ~/.useful/mysql/mysql-cheatsheet.txt"
alias umpermissions="open -e ~/.useful/mysql/permissions.txt"
alias umsubselects="open -e ~/.useful/mysql/subselects.txt"

# GOTO SPECIFIC FOLDERS
alias docs="cd ~/Documents"
alias music="cd ~/Music"
alias pics="cd ~/Pictures"
alias proj="cd ~/Projects"
alias apps="cd /Applications"
alias dl="cd ~/Downloads"
alias desk="cd ~/Desktop"

# OPEN SPECIFIC FOLDERS
alias odocs="open ~/Documents/"
alias omusic="open ~/Music/"
alias opics="open ~/Pictures/"
alias oapps="open /Applications/"
alias odl="open ~/Downloads/"
alias odesk="open ~/Desktop/"
alias oproj="open ~/Projects"
alias ohtdocs="open /var/www"
#alias ohtdocs="open ~/Projects/Web-Applications"
alias appsdevel="open /Applications/Developer"

## WEB DEVELOPMENT
alias mamp="cd /Applications/MAMP/"
alias ehosts="edit /etc/hosts"
alias vhosts="edit ${APACHE_CONF_HOSTS}"
alias httpdconf="edit ${APACHE_CONF}"
alias phperror="edit ${PHP_ERROR}"
alias starttomcat="/Applications/Developer/Tomcat/bin/startup.sh"
alias stoptomcat="/Applications/Developer/Tomcat/bin/shutdown.sh"
alias clean_xprof="rm -rf /Users/avillanueva/Projects/XHProf-Output/*"
alias webserver_paths="less ${DOTFILES}/config/webserver/paths"
alias comms="oo adium; oo limechat"

  ## DRUPAL
  alias dru='' # Default Drupal stuff.
  alias en='drush en -y'
  alias dis='drush dis -y'

# GENERATED & CUSTOM ALIASES 
source $HOME/.dotfiles/data/generated-aliases
source $HOME/.dotfiles/custom/other/custom-aliases

# WORKING WITH CUSTOM STUFF
alias ecalias="edit ~/.custom/other/custom-aliases"
alias ocustom="open ${DOTFILES}/custom"
alias escripts="open ${DOTFILES}/custom/scripts"

alias lipsum="echo -n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum lacinia egestas. Nullam auctor tortor euismod turpis egestas pretium. Aliquam ullamcorper nulla diam, a fermentum velit vehicula non. Pellentesque egestas enim vitae pellentesque pulvinar. Nam placerat dictum mattis. Nunc non augue molestie, ullamcorper dui eu, interdum nunc. In ac aliquet sapien. Cras viverra luctus nisl, nec iaculis mauris laoreet sed. Etiam eu tortor nec mauris semper accumsan at at turpis.  | pbcopy; echo copied"

## GET SPECIFIC
alias ga='git add'
alias gp='git push'
alias gpl='git pull'
alias gf='git fetch'
alias gl='git log'
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gb='git branch'
alias gc='git commit'
alias gcl='git clone'
alias gco='git checkout'
alias gpom='git push origin master'
alias gpod='git push origin dev'

if [ -f $HOME/.dotfiles/bin/git-completion.bash ]; then
   source $HOME/.dotfiles/bin/git-completion.bash
   __git_complete ga _git_add
   __git_complete gp _git_push
   __git_complete gpl _git_pull
   __git_complete gf _git_fetch
   __git_complete gl _git_log
   __git_complete gs _git_status
   __git_complete gd _git_diff
   __git_complete gb _git_branch
   __git_complete gc _git_commit
   __git_complete gcl _git_clone
   __git_complete gco _git_checkout
fi
