#!/bin/sh

#----------------------------------------------------------------
# A simple function to cleanup files within one of my drupal websites. Sometimes
function cleanupfiles() {
	PASS="root"
	mysql -uroot -p"$PASS" -e "use files; truncate file_managed; truncate watchdog"
	rm -rf /Users/avillanueva/Projects/Web-Applications/files/sites/default/files/*
}

#----------------------------------------------------------------
# Start my tomcat server which is located within this directory. I don't use tomcat anymore.
function tomcat() {
	sh /Applications/Developer/Tomcat/bin/$1.sh
}

function sqlup() {
	PASS="root"
	mysql -uroot -p"$PASS" $1 < $2
}

#----------------------------------------------------------------
# A much easier way to make many files. 
function mfile() {
	touch $2.$1
}

#----------------------------------------------------------------
# Set the title of a terminal window. 
function title() {
    echo -ne "\033]0;$1\007";
}

#----------------------------------------------------------------
# Rename a file's extension
function file_ext() {
    file=$1
    new_ext=$2
    new_basename="${file%.*}"
    #newfile "extension: ${file##*.}"
    new_file=${new_basename}.${new_ext}
    mv ${file} ${new_file}
}
