#!/bin/bash

PATHS_TO_JOIN=(
	/usr/local/bin	
	/usr/local/sbin	
	/opt/local/bin
	/opt/local/sbin
	/Applications/Mamp/Library/bin	
	/Applications/Developer/Maven/bin	
	/Applications/MAMP/bin/php/php5.2.17/bin	
	/Applications/Internet/Firefox.app/Contents/MacOS	
	${HOME}/.dotfiles/bin
	
	# Where a user adds custom environment scripts.
	${HOME}/.dotfiles/custom/scripts
)

JOINED_PATHS=""

for f in "${PATHS_TO_JOIN[@]}"
	do
		JOINED_PATHS="$JOINED_PATHS:$f"
done
