#!/bin/sh

# Some quick paths to use globally in include (source) files into bash scripts.
export DOTFILES="$HOME/.dotfiles"
export DOTFILES_CONFIG="$HOME/.dotfiles/config"
export DOTFILES_BIN="$HOME/.dotfiles/bin"
export DOTFILES_CUSTOM="$HOME/.dotfiles/custom"
export BASH_CONSTS="$HOME/.dotfiles/config/constants"
export WEBSERVER_CONSTS="$HOME/.dotfiles/config/webserver/paths"
export BASH_FUNCTIONS="$HOME/.dotfiles/config/bash_functions"

# Now do some includes.
source $HOME/.dotfiles/config/bash_includes

# ENVIROMENT VARIABLES
export PATH="$JOINED_PATHS:$PATH"
export EDITOR=vim
export JAVA_HOME="/Library/Java/Home/"
export CATALINA_HOME=/Applications/Developer/Tomcat
export HISTTIMEFORMAT="[%h/%d - %H:%M:%S] "
export LC_ALL="en_US.UTF-8"
export LANG="en_US"
#export FIGNORE=DS_Store #Ignore the DS Store files when using bash.


# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults

# Add 'killall' tab completion for common apps
complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal Twitter" killall

# If possible, add tab completion for many more commands
[ -f /etc/bash_completion ] && source /etc/bash_completion

# Use IF check to determine if using SEXY_PROMPT or not.

#http://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html
PS1="\[\e[0;32m\]\u:\[\e[0m\] [\[\e[41m\]\W\[\e[0m\]]: "
