#!/bin/sh

############################################################
# ALIASES
############################################################

if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # OS X `ls`
	colorflag="-G"
fi

# http://www.cyberciti.biz/tips/bash-aliases-mac-centos-linux-unix.html

# Keep settings files in sync. Can only be run from ~
alias syncup="sh .scripts/sync-settings-up.sh"
alias syncdown="sh .scripts/sync-settings-down.sh"

# GENERATED & CUSTOM ALIASES 
source $HOME/.dotfiles/tmp/generated-aliases
source $HOME/.custom/other/custom-aliases

# GENERAL ALIASES
alias l="ls -aGl"
alias lsd="ls -l | egrep '^d'"
alias ..="cd .."
alias sbash="source ~/.bash_profile"
alias ebash="edit ~/.bash_profile"
alias ealias="edit ~/.dotfiles/config/bash_alias"
alias htdocs="cd ~/Projects/Web-Applications"
alias spikes="cd ~/Projects/Web-Applications/spikes"
alias startup="oo adium; oo outlook; oo netbeans; oo chrome; oo limechat; oo mamp; oo spotify"
alias pushnight="oo adium; oo mail; oo chrome;"
alias maven="mvn"
alias etrash="rm -rf ~/.Trash/*"
alias staget='ssh -A -qC avillanueva@dev.publicinteractive.com -L 3310:192.168.140.106:3306'
alias am="oo activity monitor"
alias dotf="cd ~/.dotfiles"

alias ep="explode-path"

## CONVENIENCE
alias arhive="tar -zcvf"
alias unarchive="tar -zxvf"
alias size="du -sh"

## APPS
alias calc="oo calculator"
alias ff="oo firefox"
alias text="oo textedit"

## CHEAT-SHEETS
alias uuseful="open ~/.dotfiles/useful"
alias udrush="open -e ~/.useful/bash/drush.txt"
alias useful="open -e ~/.useful/bash/useful-commands.txt"
alias uarchive="open -e ~/.useful/bash/archive.txt"
alias ucron="open -e ~/.useful/bash/cron.txt"
alias udates="open -e ~/.useful/bash/dates.txt"
alias uemail="open -e ~/.useful/bash/email.txt"
alias ufile-editing="open -e ~/.useful/bash/file-editing.txt"
alias ufile-system="open -e ~/.useful/bash/file-system.txt"
alias ufiles="open -e ~/.useful/bash/files.txt"
alias uinternet="open -e ~/.useful/bash/internet.txt"
alias umisc="open -e ~/.useful/bash/misc.txt"
alias uregex="open -e ~/.useful/bash/regex.txt"
alias usystem="open -e ~/.useful/bash/system.txt"
alias usvn="open ~/.useful/svn/paths.txt"

### MYSQL
alias umcli="open -e ~/.useful/mysql/cli.txt"
alias umcounting="open -e ~/.useful/mysql/counting.txt"
alias ummisc="open -e ~/.useful/mysql/misc.txt"
alias umcheats="open -e ~/.useful/mysql/mysql-cheatsheet.txt"
alias umpermissions="open -e ~/.useful/mysql/permissions.txt"
alias umsubselects="open -e ~/.useful/mysql/subselects.txt"

# GOTO SPECIFIC FOLDERS
alias docs="cd ~/Documents"
alias music="cd ~/Music"
alias pics="cd ~/Pictures"
alias proj="cd ~/Projects"
alias apps="cd /Applications"
alias dl="cd ~/Downloads"
alias desk="cd ~/Desktop"

# OPEN SPECIFIC FOLDERS
alias odocs="open ~/Documents/"
alias omusic="open ~/Music/"
alias opics="open ~/Pictures/"
alias oapps="open /Applications/"
alias odl="open ~/Downloads/"
alias odesk="open ~/Desktop/"
alias oprojects="open ~/Projects"
alias ohtdocs="open ~/Projects/Web-Applications"
alias appsdevel="open /Applications/Developer"

## WEB DEVELOPMENT
alias mamp="cd /Applications/MAMP/"
alias ehosts="open -a textwrangler /etc/hosts"
alias vhosts="open -a textwrangler.app /Applications/MAMP/conf/apache/httpd.conf"
alias httpdconf="open /Applications/MAMP/conf/apache/httpd.conf"
alias phperror="open /Applications/MAMP/logs/php_error.log"
alias bhidden="~/.scripts/backup-hidden.sh"
alias starttomcat="/Applications/Developer/Tomcat/bin/startup.sh"
alias stoptomcat="/Applications/Developer/Tomcat/bin/shutdown.sh"
alias clean_xprof="rm -rf /Users/avillanueva/Projects/XHProf-Output/*"

  ## DRUPAL
  alias dru='' # Default Drupal stuff.
  alias en='drush en -y'
  alias dis='drush dis -y'

