#!/bin/sh
# These are a set of paths that are used by the scripts.
DOTFILES="${HOME}/.dotfiles"
HTDOCS=""
GENERATED_ALIASES="${DOTFILES}/tmp/generated-aliases"

INCLUDES=(
	bash_alias
	bash_functions
	dynamic_paths
)

# Dynamic inclusion of all the needed files.
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in "${INCLUDES[@]}";
	do
		source "${HOME}/.dotfiles/config/$file"
done

unset file