#!/bin/sh

# Clear the console buffer to take over the full screen.
clear

# This shell script demonstrates how to write interactive shell scripts
# by allowing you to get user input.  Also demonstrated is the use of
# shell functions and shell arrays, timing using SECONDS, and more!
# Written by Wayne Pollock, Tampa FL 1996

# DO INSTALL -----------------------------------------------------------------------------
echo  "1. Would you like to install the dotfiles? (yes/no)"
read CONTINUE

if [ "$CONTINUE" != "yes" ]
  then
    echo 'Stopping execution'
    exit 0
fi

# Create the custom files ----------------------------------------------------------------
clear
echo "2. Would you like to create and/or generate custom paths, aliases and scripts? (yes/no)"
echo "If so the directories will also be opened so that they can be added to."
read CUSTOM

if [ "$CUSTOM" == "yes" ]
  then
    # Create the directories.
    mkdir -p $HOME/.custom
    mkdir -p $HOME/.custom/scripts
    mkdir -p $HOME/.custom/other

    # Create the files.
    touch $HOME/.custom/other/custom-aliases
    touch $HOME/.custom/other/paths-to-generate
    touch $HOME/.dotfiles/tmp/generated-aliases
    
    echo $HOME
    open $HOME/.custom/scripts
    open $HOME/.custom/other
  else
    echo "We will skip this step";
fi

# OSX SETTINGS ---------------------------------------------------------------------------
clear
echo  "3. Would you like to use the custom osx settings? (yes/no)"
read CUSTOM_OSX

if [ "$CUSTOM_OSX" == "yes" ]
  then
    echo "Running the OSX settings."
    . $HOME/.dotfiles/config/osx-defaults
  else
    echo "We will skip this step";
fi

# BASH PROFILE ---------------------------------------------------------------------------
clear
prompt "5. The last thing to do is to create the bash profile."
#cp "${HOME}/.dotfiles/config/bash_profile" "${HOME}/.bash_profile"

# LAST NOTES ---------------------------------------------------------------------------
clear
prompt "6. For this all to work close out this session and open a new one.";
