#!/bin/bash

APACHE_DIRECTORY="/opt/local/apache2"
APACHE_CONF="/opt/local/apache2/conf/httpd.conf"
APACHE_CONF_HOSTS="/opt/local/apache2/conf/extra/httpd-vhosts.conf"
APACHE_ERROR="/opt/local/apache2/logs/error_log.log"
APACHE_ERROR_DIRECTORY="/opt/local/apache2/logs"

MYSQL_DIRECTORY="/opt/local/var/run/mysql5/ "
MYSQL_CONF=""
MYSQL_ERROR="/opt/local/var/log/mysql5/"

PHP_DIRECTORY="/opt/local/etc/php5"
PHP_CONF="/opt/local/etc/php5/php.ini"
PHP_ERROR="/opt/local/etc/php5/php_error.log"