#!/bin/sh

# INSTALL MYSQL
sudo port install mysql5-server

# Setup. Do all of this to make sure that it works.
# http://systems.takizo.com/2008/06/09/mysql5-server-cannot-start-on-apple-mac-leopard/
# https://lists.macosforge.org/pipermail/macports-users/2010-October/022279.html
#	  sudo -u mysql mysql_install_db5
#	  User is _mysql NOT mysql

# Do the inital setup. DO NOT do the one above as that doesn't seem to work.
sudo mysql_install_db5

# Setup the main database
sudo chown -R mysql:mysql /opt/local/var/db/mysql5/ 
sudo chown -R mysql:mysql /opt/local/var/run/mysql5/ 
sudo chown -R mysql:mysql /opt/local/var/log/mysql5/ 

# This is to create a password for root. Though this is for local this isn't needed.
mysqladmin -u root password 'root'

# Some other quick resources to use.
# http://www.mail-archive.com/macports-users@lists.macosforge.org/msg21646.html
# http://davidchristiansblog.blogspot.com/2012/02/mysql-fails-with-shell-init-error.html

# Some notes on starting and stopping
#sudo /opt/local/etc/LaunchDaemons/org.macports.mysql5/mysql5.wrapper start
#sudo /opt/local/etc/LaunchDaemons/org.macports.mysql5/mysql5.wrapper stop
