#!/bin/sh

# Make this a file that I can just go ahead and symlink (or copy).
# Take a look at the port-80.plist file.

# RUN WITH PORT 80
# You may notice that httpd.conf is running Apache on port 8080, but the above
# are using port 80. The next two commands will create and load a firewall rule 
# to forward 8080 requests to 80. The end result is that we can use port 80 in 
# VirtualHosts without needing to run Apache as root.

# The following single command will create the file
# /Library/LaunchDaemons/co.echo.httpdfwd.plist as root, and owned by root, 
# since it needs elevated privileges.

ln -s port-80.plist /Library/LaunchDaemons/co.echo.httpdfwd.plist

# This file will be loaded on login and set up the 80->8080 port forward, but we
# can load it manually now so we don't need to log out and back in.

sudo launchctl load -w /Library/LaunchDaemons/co.echo.httpdfwd.plist
