#!/bin/sh
# http://blog.ryanparman.com/2009/07/11/installing-php-5-3-with-mysqlnd-on-mac-os-x-with-macports/

# First install PHP with some variants.
sudo port install php5 +apache2 +fastcgi +pear

# Add a bunch of extensions that we'll want to make our lives easier.
sudo port install php5-apc \
	php5-curl \
	php5-gd \
	php5-http \
	php5-iconv \
	php5-imagick \
	php5-mbstring \
	php5-mcrypt \
	php5-memcached \
	php5-mysql +mysqlnd  \
	php5-openssl \
	php5-tidy \
	php-xdebug \
	php5-posix

#
sudo mkdir /www-config && \
cd /www-config && \
sudo ln -s /opt/local/apache2/bin/apachectl /www-config/apachectl && \

sudo ln -s /opt/local/var/db/php5/ /www-config/php-ini && \
sudo ln -s /opt/local/etc/php5/php.ini /www-config/php.ini