#! /bin/sh
# Setup iterm.

cp ${HOME}/Library/Preferences/com.googlecode.iterm2.plist ${HOME}/Desktop/com.googlecode.iterm2.plist.old
rm cp ${HOME}/Library/Preferences/com.googlecode.iterm2.plist
ln -s ${HOME}/.dotfiles/config/misc/com.googlecode.iterm2.plist ${HOME}/Library/Preferences/com.googlecode.iterm2.plist

echo "Made a symlink for iterm2."