#!/bin/sh

ln -s ${HOME}/.dotfiles/config/bash/bash_profile ${HOME}/.bash_profile;
ln -s ${HOME}/.dotfiles/config/bash/bash_rc ${HOME}/.bashrc;
ln -s ${HOME}/.dotfiles/config/bash/bash_inputrc ${HOME}/.inputrc
