#!/bin/sh

APACHE_DIRECTORY="/opt/local/apache2"
APACHE_CONF="/opt/local/apache2/conf/httpd.conf"
APACHE_CONF_HOSTS="/opt/local/apache2/conf/extra/httpd-vhosts.conf"
APACHE_ERROR="/opt/local/apache2/logs/error_log.log"
APACHE_ERROR_DIRECTORY="/opt/local/apache2/logs"

MYSQL_DIRECTORY="/opt/local/var/run/mysql5/ "
MYSQL_CONF=""
MYSQL_ERROR="/opt/local/var/log/mysql5/"

PHP_DIRECTORY="/opt/local/etc/php5"
PHP_CONF="/opt/local/etc/php5/php.ini"
PHP_ERROR="/opt/local/etc/php5/php_error.log"

if [[ "`whoami`" != "root" ]]; 
  then
    echo "This script uses macports and in order to run macports you need to be running as root."
    exit 0
fi

if hash port 2>/dev/null;
  then
    sudo port selfupdate;

    # PHP ----------------------------------------------------------------------
    echo "Install PHP"

    # http://blog.ryanparman.com/2009/07/11/installing-php-5-3-with-mysqlnd-on-mac-os-x-with-macports/

    # First install PHP with some variants.
    sudo port install php5 +apache2 +fastcgi +pear

    # Add a bunch of extensions that we'll want to make our lives easier.
    sudo port install php5-apc \
      php5-curl \
      php5-gd \
      php5-http \
      php5-iconv \
      php5-imagick \
      php5-mbstring \
      php5-mcrypt \
      php5-memcached \
      php5-mysql +mysqlnd  \
      php5-openssl \
      php5-tidy \
      php-xdebug \
      php5-posix

    #
    # sudo mkdir /www-config && \
    # cd /www-config && \
    # sudo ln -s /opt/local/apache2/bin/apachectl /www-config/apachectl && \
    # sudo ln -s /opt/local/var/db/php5/ /www-config/php-ini && \
    # sudo ln -s /opt/local/etc/php5/php.ini /www-config/php.ini

    # MYSQL --------------------------------------------------------------------
    echo "Mysql"
    # INSTALL MYSQL
    sudo port install mysql5-server

    # Some other quick resources to use.
    # http://www.mail-archive.com/macports-users@lists.macosforge.org/msg21646.html
    # http://davidchristiansblog.blogspot.com/2012/02/mysql-fails-with-shell-init-error.html

    # Some notes on starting and stopping
    #sudo /opt/local/etc/LaunchDaemons/org.macports.mysql5/mysql5.wrapper start
    #sudo /opt/local/etc/LaunchDaemons/org.macports.mysql5/mysql5.wrapper stop

    # Setup. Do all of this to make sure that it works.
    # http://systems.takizo.com/2008/06/09/mysql5-server-cannot-start-on-apple-mac-leopard/
    # https://lists.macosforge.org/pipermail/macports-users/2010-October/022279.html
    #   sudo -u mysql mysql_install_db5
    #   User is _mysql NOT mysql

    # Do the inital setup. DO NOT do the one above as that doesn't seem to work.
    sudo mysql_install_db5

    # Setup the main database
    sudo chown -R mysql:mysql /opt/local/var/db/mysql5/ 
    sudo chown -R mysql:mysql /opt/local/var/run/mysql5/ 
    sudo chown -R mysql:mysql /opt/local/var/log/mysql5/ 

    # This is to create a password for root. Though this is for local this isn't needed.
    mysqladmin -u root password 'root'

    # APACHE -------------------------------------------------------------------
    echo "Apache"
    sudo port install apache2

    # CONFIGURATIONS -----------------------------------------------------------
    echo "Make a symlink for php.ini"
    echo "Make a symlink for httpd.conf"
    echo "Do the mysql.sock or something ..."
else
  echo "Hey, you need macports on this system bro."
  exit;
fi
