#!/bin/sh

rm ${HOME}/.bash_profile;
rm ${HOME}/.bashrc;
rm ${HOME}/.inputrc

ln -s ${HOME}/.dotfiles/config/bash/bash_profile ${HOME}/.bash_profile;
ln -s ${HOME}/.dotfiles/config/bash/bash_rc ${HOME}/.bashrc;
ln -s ${HOME}/.dotfiles/config/bash/bash_inputrc ${HOME}/.inputrc
