#!/bin/sh

MODULE_DIR=$HOME/.emacs.d
THEMES_DIR=$HOME/.emacs.d/themes

if hash git 2>/dev/null;
  then
    # Check if the directory exists. Then empty it out. Otherwise create it.
    rm -rf $MODULE_DIR
    mkdir $MODULE_DIR

    echo "\nDownloading Solarized"
    git clone git@github.com:illusori/emacs-color-theme-solarized.git $THEMES_DIR/solarized
else
  echo "Git does not exist on this system"
  exit;
fi
