#!/bin/sh

MODULE_DIR=$HOME/.emacs.d
THEMES_DIR=$HOME/.emacs.d/themes

if hash git 2>/dev/null;
  then
    # Check if the directory exists. Then empty it out. Otherwise create it.
    rm -rf $MODULE_DIR
    mkdir $MODULE_DIR

    echo "\nDownloading Company"
    # git clone http://www.dr-qubit.org/git/predictive.git $MODULE_DIR/predictive;
    git clone git@github.com:company-mode/company-mode.git $MODULE_DIR/company;

    echo "\nDownloading autopair";
    git clone git@github.com:capitaomorte/autopair.git $MODULE_DIR/autopair

    echo "\nDownloading Bcycle"
    git clone git@github.com:mrpotatoes/bcycle.git $MODULE_DIR/bcycle

    echo "\nDownloading Webmode"
    git clone git@github.com:fxbois/web-mode.git $MODULE_DIR/webmode

    echo "\nDownloading flycheck, submodules and deps"
    git clone https://github.com/flycheck/flycheck.git $MODULE_DIR/flycheck
    git clone git@github.com:rejeep/f.el.git $MODULE_DIR/f
    git clone git@github.com:magnars/s.el.git $MODULE_DIR/s
    git clone git@github.com:magnars/dash.el.git $MODULE_DIR/dash
    git clone git@github.com:yuutayamada/flycheck-tip.git $MODULE_DIR/flycheck-tip

    echo "\nDownloading YaSnippet"
    git clone git@github.com:capitaomorte/yasnippet.git $MODULE_DIR/yasnippet

    echo "\nDownloading Solarized"
    git clone git@github.com:illusori/emacs-color-theme-solarized.git $THEMES_DIR/solarized

    echo "\nDownloading Git Gutter"
    git clone git@github.com:syohex/emacs-git-gutter.git $MODULE_DIR/git-gutter

    echo "\nDownloading Indicators.el"
    git clone git@github.com:Fuco1/indicators.el.git $MODULE_DIR/indicators

    echo "\nDownloading Magit"
    git clone git@github.com:magit/magit.git $MODULE_DIR/magit

    echo "\nDownloading Multiple Cursors"
    git clone git@github.com:emacsmirror/multiple-cursors.git $MODULE_DIR/multiple-cursors

    echo "\nDownloading the misc modules that I have on my repo"
    git clone git@github.com:mrpotatoes/emacs-modules-mirror.git $MODULE_DIR/emacs-modules-mirror

    echo "\nDownloading the php mode module."
    git clone https://github.com/ejmr/php-mode $MODULE_DIR/php-mode

    # http://emacsrocks.com/e09.html
    echo "\nDownloading the expand-region module."
    git clone git@github.com:magnars/expand-region.el.git $MODULE_DIR/expand-region

    echo "\nDownloading a custom mk-project module."
    git clone git@github.com:mrpotatoes/mk-project.git $MODULE_DIR/mk-project

    echo "\nDownloading the highlight-symbol module";
    git clone git@github.com:nschum/highlight-symbol.el.git $MODULE_DIR/highlight-symbol

    echo "\nDownloading the hisdeshow-org module";
    git clone git://github.com/secelis/hideshow-org.git $MODULE_DIR/hideshow-org

    echo "\nDownloading a better point moving module."
    git clone ssh://hg@bitbucket.org/jpkotta/syntax-subword

    echo "\nDownloading the jade-mode module";
    git clone https://github.com/brianc/jade-mode.git $MODULE_DIR/jade-mode

    echo "\nDownloading the Directory Tree module";
    git clone git@github.com:mrpotatoes/emacs-dirtree.git $MODULE_DIR/dirtree

    echo "\nDownloading the Ido Vertical module";
    git clone git@github.com:gempesaw/ido-vertical-mode.el.git $MODULE_DIR/ido-vertical-mode

    echo "\nDownloading Markdown Mode";
    git clone http://jblevins.org/git/markdown-mode.git $MODULE_DIR/markdown-mode

    echo "\nDownloading JS2 Mode";
    git clone git@github.com:mooz/js2-mode.git $MODULE_DIR/js2-mode
else
  echo "Git does not exist on this system"
  exit;
fi
